language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.4

gemfile:
  - gemfiles/actionmailer3_2.gemfile
  - gemfiles/actionmailer4_0.gemfile
  - gemfiles/actionmailer4_1.gemfile
  - gemfiles/actionmailer4_2.gemfile
